[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "ferret"
author = "James Elford"
author-email = "james.p.elford@gmail.com"
home-page = "https://github.com/jelford/ferret"

[tool.flit.scripts]
ferret = "ferret:main"
